#!/usr/bin/env python3
"""Render a TradingAgentsCC analysis JSON as a single markdown report.

Input JSON schema is identical to `render_html.py` (see that file for layout)."""

import itertools
import json
import os
import sys


LABELS = {
    "ko": {
        "phase1_title": "📊 Phase 1: Analyst Team",
        "phase2_title": "🔬 Phase 2: Research Team Debate",
        "phase3_title": "💹 Phase 3: Trading Plan",
        "phase4_title": "⚖️ Phase 4: Risk Management",
        "phase5_title": "🎯 Phase 5: Final Decision",
        "round": "라운드",
        "rm_synthesis": "Research Manager 최종 합성",
        "trading_checklist": "트레이딩 체크리스트",
        "decision_reasons": "결정 근거",
        "full_text": "전문",
        "header_date": "Date",
        "header_decision": "Decision",
        "header_generated_by": "Generated by",
        "header_generator": "Claude Code Multi-Agent System",
        "header_recommendation": "Recommendation",
        "report_saved": "보고서 저장됨",
    },
    "en": {
        "phase1_title": "📊 Phase 1: Analyst Team",
        "phase2_title": "🔬 Phase 2: Research Team Debate",
        "phase3_title": "💹 Phase 3: Trading Plan",
        "phase4_title": "⚖️ Phase 4: Risk Management",
        "phase5_title": "🎯 Phase 5: Final Decision",
        "round": "Round",
        "rm_synthesis": "Research Manager Synthesis",
        "trading_checklist": "Trading Checklist",
        "decision_reasons": "Decision Reasons",
        "full_text": "Full Text",
        "header_date": "Date",
        "header_decision": "Decision",
        "header_generated_by": "Generated by",
        "header_generator": "Claude Code Multi-Agent System",
        "header_recommendation": "Recommendation",
        "report_saved": "Report saved",
    },
}


def detect_decision(final_decision: str) -> str:
    """Return one of BUY / SELL / HOLD based on the final-decision text."""
    upper = final_decision.upper()
    if "BUY" in upper or "매수" in final_decision:
        return "BUY"
    if "SELL" in upper or "매도" in final_decision:
        return "SELL"
    return "HOLD"


def _checklist(items: list[str]) -> str:
    return "".join(f"- [ ] {item}\n" for item in items)


def _phase1(r: dict, L: dict) -> str:
    parts = [f"## {L['phase1_title']}\n\n"]
    for key in ("market", "news", "fundamentals", "social"):
        body = (r.get(key) or "").strip()
        if body:
            parts.append(body + "\n\n---\n\n")
    return "".join(parts)


def _phase2(r: dict, L: dict) -> str:
    bulls = r.get("bull") or []
    bears = r.get("bear") or []
    rounds = max(len(bulls), len(bears))
    parts = [f"## {L['phase2_title']} ({rounds} {L['round']})\n\n"]
    for i, (b, br) in enumerate(itertools.zip_longest(bulls, bears, fillvalue=""), 1):
        parts.append(f"### {L['round']} {i} — 🐂 Bull Researcher\n\n{b}\n\n")
        parts.append(f"### {L['round']} {i} — 🐻 Bear Researcher\n\n{br}\n\n")
    plan = (r.get("investment_plan") or "").strip()
    parts.append(f"### {L['rm_synthesis']}\n\n{plan}\n\n---\n\n")
    return "".join(parts)


def _phase3(r: dict, L: dict) -> str:
    parts = [f"## {L['phase3_title']}\n\n"]
    parts.append((r.get("trading_plan") or "").strip() + "\n\n")
    checklist = r.get("trading_checklist") or []
    if checklist:
        parts.append(f"### {L['trading_checklist']}\n\n")
        parts.append(_checklist(checklist))
        parts.append("\n")
    parts.append("---\n\n")
    return "".join(parts)


def _phase4(r: dict, L: dict) -> str:
    parts = [f"## {L['phase4_title']}\n\n"]
    for label, key in (
        ("⚡ Aggressive", "aggressive_risk"),
        ("🛡️ Conservative", "conservative_risk"),
        ("⚖️ Neutral", "neutral_risk"),
    ):
        body = (r.get(key) or "").strip()
        parts.append(f"### {label}\n\n{body}\n\n")
    parts.append("---\n\n")
    return "".join(parts)


def _phase5(r: dict, decision: str, L: dict) -> str:
    parts = [f"## {L['phase5_title']}\n\n**{L['header_recommendation']}: {decision}**\n\n"]
    reasons = r.get("decision_reasons") or []
    if reasons:
        parts.append(f"### {L['decision_reasons']}\n\n")
        parts.append(_checklist(reasons))
        parts.append("\n")
    final = (r.get("final_decision") or "").strip()
    if final:
        parts.append(f"### {L['full_text']}\n\n" + final + "\n")
    return "".join(parts)


def render_markdown(data: dict, lang: str = "ko") -> str:
    L = LABELS[lang]
    ticker = data["ticker"]
    date = data["date"]
    r = data.get("reports") or {}
    decision = detect_decision(r.get("final_decision", ""))

    header = (
        f"# TradingAgentsCC Analysis: {ticker}\n\n"
        f"**{L['header_date']}**: {date}  |  **{L['header_decision']}**: **{decision}**  |  "
        f"**{L['header_generated_by']}**: {L['header_generator']}\n\n---\n\n"
    )
    return header + _phase1(r, L) + _phase2(r, L) + _phase3(r, L) + _phase4(r, L) + _phase5(r, decision, L)


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Render TradingAgentsCC Markdown report.")
    parser.add_argument("input", help="Path to analysis JSON")
    parser.add_argument("output", help="Path to write Markdown output")
    parser.add_argument("--lang", choices=["ko", "en"], default="ko",
                        help="Output language for section labels (default: ko)")
    args = parser.parse_args()

    with open(args.input, encoding="utf-8") as f:
        data = json.load(f)
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(render_markdown(data, lang=args.lang))
    print(f"✅ {LABELS[args.lang]['report_saved']}: {args.output}")


if __name__ == "__main__":
    main()
